In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import *

##  the below table reprasents the students studying  hours and  pass are fail

In [5]:
dict={
    
    'x':np.arange(1,70,3),
    'y':np.random.choice([1,0],size=23)
}

In [6]:
dataframe=pd.DataFrame(dict)
dataframe

     x  y
0    1  1
1    4  0
2    7  1
3   10  1
4   13  1
5   16  1
6   19  1
7   22  0
8   25  1
9   28  1
10  31  0
11  34  0
12  37  0
13  40  1
14  43  1
15  46  0
16  49  0
17  52  0
18  55  1
19  58  0
20  61  1
21  64  1
22  67  1

$$xi = mx + c$$
$$sigmoid = \frac{1}{1+e^{-xi}}$$

In [7]:
class Logistic_Regression():
    def __inint__(self,dataframe,m,c):
        self.dataframe=dataframe
        self.y_org=None
        self.y_pred=None
         
    def sigmoid(self):
        self.m=2.4
        self.c=-0.8
        X=[]
        for value in dataframe['x'].values:
            X.append(self.m*(value)+self.c)
        pre=[]
        for v in X:    
            pre.append(1/(1+np.exp(-v))) 
        self.y_pred=[]
        for pri in pre:   
            if pri > 0.5:
                self.y_pred.append(1)
            else:
                y_pred.append(0)
        self.y_org=dataframe['y'].values
        return self.y_org , self.y_pred

    def accuracy(self):
        self.correct=0
        for Y_org,Y_pre in zip(self.y_org,self.y_pred):
            if Y_org==Y_pre:
                self.correct+=1
        print(f"Total Correct {self.correct}, Total length {len(self.y_pred)}")
        return f"{(self.correct/len(self.y_pred))*100}%"
        
        
    
obj=Logistic_Regression()
obj.sigmoid()
obj.accuracy()

Total Correct 14, Total length 23

'60.86956521739131%'